# Generated by Django 2.2.2 on 2019-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190705_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.SmallIntegerField(blank=True, default=0, help_text='年龄', null=True, verbose_name='年龄'),
        ),
    ]
