# Generated by Django 2.2.2 on 2019-07-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190705_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, default='1000-09-09', null=True, verbose_name='生日'),
        ),
    ]
