# Generated by Django 2.2.2 on 2019-07-05 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190705_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='education_degree',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='graduation_result',
            field=models.CharField(choices=[('1', '已毕业'), ('2', '未毕业')], default=1, help_text='1-启用/2-停用', max_length=50, verbose_name='毕业结业状态'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='education_degree',
            field=models.ForeignKey(help_text='学历信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EducationDegree_StudentInfo', to='webapp.EducationDegree', verbose_name='学历信息'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='middle_school',
            field=models.CharField(blank=True, default='', help_text='初级中学名称', max_length=200, null=True, verbose_name='初级中学名称'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='graduation_status',
            field=models.IntegerField(default=0, help_text='毕业证件状态', null=True, verbose_name='毕业证件状态'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='unit_address',
            field=models.CharField(blank=True, default='', help_text='单位地址', max_length=200, null=True, verbose_name='单位地址'),
        ),
    ]
