# Generated by Django 2.2.2 on 2019-07-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190705_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id_card_address',
            field=models.CharField(blank=True, help_text='身份证住址', max_length=200, null=True, verbose_name='身份证住址'),
        ),
    ]
