# Generated by Django 2.2.2 on 2019-07-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190705_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='apprentice_end',
            field=models.DateField(help_text='学徒期结束', null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='apprentice_start',
            field=models.DateField(help_text='学徒期开始', null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='current_issuance_time',
            field=models.DateField(blank=True, null=True, verbose_name='本次考核职业资格证书发行时间'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='graduation_time',
            field=models.DateField(blank=True, null=True, verbose_name='毕业时间'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='issuance_time',
            field=models.DateField(blank=True, null=True, verbose_name='原职业资格证发放时间'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='start_the_work_of_this_occupation',
            field=models.DateField(blank=True, null=True, verbose_name='从事本职业工作开始时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='start_working_date',
            field=models.DateField(blank=True, help_text='起始工作时间,不用职位分类', null=True, verbose_name='起始工作时间'),
        ),
    ]
