# Generated by Django 2.2.2 on 2019-07-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20190705_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, help_text='常住住址', max_length=200, null=True, verbose_name='常住住址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='contact_number',
            field=models.CharField(blank=True, help_text='联系电话', max_length=50, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id_number',
            field=models.CharField(blank=True, help_text='身份证件号码信息', max_length=20, null=True, verbose_name='身份证件号码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='political_status',
            field=models.CharField(blank=True, choices=[('0', '中共党员'), ('1', '中共预备党员'), ('2', '共青团员'), ('3', '民革党员'), ('4', '民盟盟员'), ('5', '民建会员'), ('6', '民进会员'), ('7', '农工党党员'), ('8', '致公党党员'), ('9', '九三学社社员'), ('10', '台盟盟员'), ('11', '无党派人士'), ('12', '群众(普通居民)')], default=12, help_text='政治面貌:01 中共党员,02 中共预备党员,03共青团员,04民革党员,05民盟盟员,06民建会员,07民进会员,08农工党党员, 09致公党党员,10九三学社社员,11台盟盟员,12无党派人士,13群众（现称普通居民，与居民身份证相对应）', max_length=20, null=True, verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='postal_code',
            field=models.CharField(blank=True, help_text='邮政编码', max_length=20, null=True, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='working_year',
            field=models.SmallIntegerField(blank=True, default=0, help_text='小于10个月，默认为小数年。如果大于10个月约等于1年', null=True, verbose_name='参加工作年限'),
        ),
    ]
