# Generated by Django 2.2.2 on 2019-07-06 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20190706_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='user_info',
            field=models.ForeignKey(blank=True, help_text='学员基本信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webapp_studentinfo_UserInfo', to='webapp.UserInfo', verbose_name='学员基本信息'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='work_training',
            field=models.TextField(blank=True, help_text='个人工作及职业培训简历', max_length=500, null=True, verbose_name='个人工作及职业培训简历'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='education_degree',
            field=models.ForeignKey(blank=True, help_text='学历信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EducationDegree_StudentInfo', to='webapp.EducationDegree', verbose_name='学历信息'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='hukou_city',
            field=models.ForeignKey(blank=True, help_text='市信息ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_UserInfo', to='webapp.ProvinceCityCountry', verbose_name='市信息ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='hukou_county',
            field=models.ForeignKey(blank=True, help_text='县信息ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_UserInfo', to='webapp.ProvinceCityCountry', verbose_name='县信息ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='hukou_province',
            field=models.ForeignKey(blank=True, help_text='省信息ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_UserInfo', to='webapp.ProvinceCityCountry', verbose_name='省信息ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nation_info',
            field=models.ForeignKey(blank=True, help_text='民族信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NationInfo_UserInfo', to='webapp.NationInfo', verbose_name='民族信息'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='two_inch_photo',
            field=models.ForeignKey(blank=True, help_text='二寸证件照片信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Picture_UserInfo', to='webapp.Picture', verbose_name='二寸证件照片信息'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='unit_nature',
            field=models.ForeignKey(blank=True, help_text='单位性质信息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UnitNature_UserInfo', to='webapp.UnitNature', verbose_name='单位性质信息'),
        ),
    ]
