# Generated by Django 2.2.2 on 2019-07-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20190706_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='apprentice_end',
            field=models.DateField(blank=True, help_text='学徒期结束', null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='apprentice_month',
            field=models.IntegerField(default=0, help_text='学徒期月', null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='apprentice_start',
            field=models.DateField(blank=True, help_text='学徒期开始', null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='apprentice_year',
            field=models.IntegerField(default=0, help_text='学徒期年', null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='career_life',
            field=models.SmallIntegerField(blank=True, default=0, help_text='本次申报职业年限', null=True, verbose_name='本次申报职业年限'),
        ),
    ]
