# Generated by Django 2.2.2 on 2019-07-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20190707_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='original_certificate_worker_year',
            field=models.IntegerField(blank=True, default=0, help_text='从事本职业工作年限（后），获取资格证之后', null=True, verbose_name='从事本职业工作年限（后）'),
        ),
    ]
