# Generated by Django 2.2.2 on 2019-07-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20190707_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='main_occupation',
            field=models.CharField(blank=True, help_text='从事职业', max_length=50, null=True, verbose_name='从事职业'),
        ),
    ]
