# Generated by Django 2.2.2 on 2019-07-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20190707_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='cancel_status',
            field=models.CharField(choices=[('0', '申请撤销'), ('1', '未申请撤销')], default=1, help_text='0 申请撤销 1 未申请撤销,一旦撤销,负责人将无法编辑修改,信息的操作权限将转移到下一级的学员手中', max_length=50, verbose_name='提交撤销状态'),
        ),
    ]
