# Generated by Django 2.2.2 on 2019-07-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20190708_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='number',
            field=models.CharField(blank=True, default='', help_text='教师编号', max_length=50, null=True, verbose_name='教师编号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, default='', help_text='常住住址', max_length=200, null=True, verbose_name='常住住址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='contact_number',
            field=models.CharField(blank=True, default='', help_text='联系电话', max_length=50, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id_card_address',
            field=models.CharField(blank=True, default='', help_text='身份证住址', max_length=200, null=True, verbose_name='身份证住址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id_number',
            field=models.CharField(blank=True, default='', help_text='身份证件号码信息', max_length=20, null=True, verbose_name='身份证件号码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='main_occupation',
            field=models.CharField(blank=True, default='', help_text='从事职业', max_length=50, null=True, verbose_name='从事职业'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='postal_code',
            field=models.CharField(blank=True, default='', help_text='邮政编码', max_length=20, null=True, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='work_unit',
            field=models.CharField(blank=True, default='', help_text='工作单位信息,可为空！', max_length=100, null=True, verbose_name='工作单位'),
        ),
    ]
