# Generated by Django 2.2.2 on 2019-07-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20190709_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='teacher_number',
            field=models.CharField(blank=True, help_text='单位负责报名的负责人编号', max_length=20, null=True, verbose_name='单位负责报名的负责人编号'),
        ),
    ]
