# Generated by Django 2.2.2 on 2019-07-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20190709_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='chemical_worker',
            field=models.CharField(choices=[('1', '化工'), ('2', '非化工')], default=2, help_text='1 已支付 2 未支付,一旦支付,学员信息将进入学习状态', max_length=50, verbose_name='化工'),
        ),
    ]
