# Generated by Django 2.2.2 on 2019-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_studentinfo_chemical_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='course_hours',
            field=models.IntegerField(default=0, help_text='培训课时', null=True),
        ),
    ]
