# Generated by Django 2.2.2 on 2019-07-11 01:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_studentinfo_course_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='teacher_cancel_result',
            field=models.CharField(choices=[('1', '申请撤销成功'), ('2', '申请撤销失败')], default=2, help_text='1 申请撤销成功 2 申请撤销失败,一旦管理员同意注销,将无法编辑修改,信息的操作权限将转移到对应的负责人手中', max_length=50, verbose_name='负责人申请注销状态'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='teacher_cancel_status',
            field=models.CharField(choices=[('1', '申请撤销'), ('2', '未申请撤销')], default=2, help_text='1 申请撤销 2 未申请撤销,一旦申请被受理,负责人将无法编辑修改此纪录,信息的操作权限将转移到上一级的管理员手中', max_length=50, verbose_name='负责人提交注销申请'),
        ),
        migrations.CreateModel(
            name='SchoolTerm',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='学期ID')),
                ('school_term_name', models.CharField(blank=True, default='', help_text='学期名字', max_length=50, null=True, verbose_name='学期名字')),
                ('school_term_start', models.DateField(blank=True, help_text='学期开始时间，只有到了新学期时间到才能报名', null=True, verbose_name='新学期开始时间')),
                ('school_term_end', models.DateField(blank=True, help_text='起始工作时间,新学期结束系统无法报名', null=True, verbose_name='新学期开始时间')),
                ('explain', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user_info', models.ForeignKey(blank=True, help_text='学员基本信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webapp_schoolterm_UserInfo', to='webapp.UserInfo', verbose_name='学员基本信息')),
                ('user_operator', models.ForeignKey(blank=True, help_text='操作用户记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webapp_schoolterm_Operator', to='webapp.RegisterUserInfo', verbose_name='操作用户')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
