# Generated by Django 2.2.2 on 2019-07-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20190711_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolterm',
            name='status',
            field=models.CharField(choices=[('1', '启用'), ('2', '停用')], default=1, help_text='1-启用/2-停用', max_length=50, verbose_name='报名系统状态'),
        ),
    ]
