# Generated by Django 2.2.2 on 2019-07-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_schoolterm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='school_term',
            field=models.ForeignKey(blank=True, help_text='负责人基本信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webapp_studentinfo_TeacherInfo', to='webapp.SchoolTerm', verbose_name='负责人基本信息'),
        ),
    ]
