# Generated by Django 2.2.2 on 2019-07-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_studentinfo_school_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='status',
            field=models.CharField(choices=[('1', '启用'), ('2', '停用')], default=1, help_text='1-启用/2-停用', max_length=50, verbose_name='负责人状态'),
        ),
    ]
