# Generated by Django 2.2.2 on 2019-07-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_teacherinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolterm',
            name='students_status_not',
            field=models.IntegerField(default=0, help_text='本期处于异常状态的学员', null=True, verbose_name='本期处于异常状态的学员'),
        ),
        migrations.AddField(
            model_name='schoolterm',
            name='students_status_yes',
            field=models.IntegerField(default=0, help_text='本期处于正常状态的学员', null=True, verbose_name='本期处于正常状态的学员'),
        ),
    ]
