# Generated by Django 2.2.2 on 2019-07-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_auto_20190713_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruserinfo',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RoleInfo_RegisterUserInfo', to='webapp.RoleInfo'),
        ),
        migrations.AddField(
            model_name='roleinfo',
            name='role_alias',
            field=models.CharField(default='', max_length=50, verbose_name='角色别名（中文）'),
        ),
        migrations.AlterField(
            model_name='roleinfo',
            name='role_name',
            field=models.CharField(default='', max_length=50, verbose_name='角色名称（英文）'),
        ),
    ]
