# Generated by Django 2.2.2 on 2019-07-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_auto_20190713_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruserinfo',
            name='roles',
        ),
    ]
