# Generated by Django 2.2.2 on 2019-07-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_remove_registeruserinfo_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruserinfo',
            name='status',
            field=models.CharField(choices=[('1', '启用'), ('2', '停用')], default=1, help_text='1-启用/2-停用', max_length=50, verbose_name='注册用户的状态'),
        ),
    ]
