# Generated by Django 2.2.2 on 2019-07-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_auto_20190716_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewaudit',
            name='modify_time',
        ),
    ]
