# Generated by Django 2.2.2 on 2019-07-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_remove_interviewaudit_modify_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewaudit',
            name='operation_message',
            field=models.TextField(blank=True, default='', verbose_name='日志信息'),
        ),
    ]
