# Generated by Django 2.2.2 on 2019-07-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_auto_20190716_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewaudit',
            name='operation_level',
            field=models.CharField(choices=[('1', '查询'), ('2', '增加'), ('3', '修改状态'), ('4', '修改内容'), ('5', '删除'), ('6', '注册'), ('7', '登陆'), ('8', '退出'), ('9', '下载'), ('10', '上传')], default=1, help_text='1 正常 2 异常,异常应在备注中说明', max_length=50, verbose_name='学业状态'),
        ),
    ]
