# Generated by Django 2.2.2 on 2019-07-21 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_interviewaudit_operation_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='系统信息ID')),
                ('message', models.TextField(default='', max_length=500, verbose_name='发送的消息')),
                ('send_status', models.CharField(choices=[('1', '成功'), ('2', '失败')], default=1, help_text='1 成功 2 失败,发送成功,将以系统消息的方式提示接收方', max_length=50, verbose_name='发送状态')),
                ('receive_status', models.CharField(choices=[('1', '已查看'), ('2', '未查看')], default=2, help_text='1 已查看 2 未查看,查看之后将不再会被推送为系统消息', max_length=50, verbose_name='查看状态')),
                ('feedback_status', models.CharField(choices=[('1', '已确认'), ('2', '未确认')], default=2, help_text='1 已确认表明本次通话的结束 2 未确认表明本次信息已查看但但未确认信息给回馈者', max_length=50, verbose_name='确认状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('feedback_message', models.ForeignKey(blank=True, help_text='确认并回复消息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegisterUserInfo_Sender', to='webapp.SystemMessage', verbose_name='确认并回复消息')),
                ('register_receiver', models.ForeignKey(blank=True, help_text='接收方', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegisterUserInfo_Receiver', to='webapp.RegisterUserInfo', verbose_name='接收方')),
                ('register_sender', models.ForeignKey(blank=True, help_text='发送方', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegisterUserInfo_Sender', to='webapp.RegisterUserInfo', verbose_name='发送方')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
