# Generated by Django 2.2.2 on 2019-07-21 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_systemmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmessage',
            name='register_receiver',
        ),
        migrations.RemoveField(
            model_name='systemmessage',
            name='register_sender',
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, help_text='接收方', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegisterUserInfo_Receiver', to='webapp.UserInfo', verbose_name='接收方'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='发送方', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegisterUserInfo_Sender', to='webapp.UserInfo', verbose_name='发送方'),
        ),
    ]
