# Generated by Django 2.2.2 on 2019-07-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_auto_20190721_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessage',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
    ]
