# Generated by Django 2.2.2 on 2019-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_systemmessage_explain'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessage',
            name='hidden_status',
            field=models.CharField(choices=[('1', '已隐藏'), ('2', '未隐藏')], default=2, help_text='1 已隐藏将不会显示在查看列表中 2 未隐藏将显示在查看列表中', max_length=50, verbose_name='隐藏状态'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='message_level',
            field=models.CharField(choices=[('1', '常规'), ('2', '预警'), ('3', '紧急')], default='', help_text='消息级别', max_length=50, null=True, verbose_name='消息级别'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='message_range',
            field=models.CharField(choices=[('1', '系统公告'), ('2', '系统管理员'), ('3', '全体负责人'), ('4', '负责人'), ('5', '全体学员'), ('6', '负责人管辖全体学员'), ('7', '学员')], default='', help_text='消息发送范围', max_length=50, null=True, verbose_name='消息发送范围'),
        ),
    ]
