# Generated by Django 2.2.2 on 2019-07-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_auto_20190723_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessage',
            name='reply_status',
            field=models.CharField(choices=[('1', '已确认并回复'), ('2', '未确认未回复')], default=2, help_text='1 已确认并回复 2 未确认未回复', max_length=50, verbose_name='确认并回复状态'),
        ),
    ]
