# Generated by Django 2.2.2 on 2019-08-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0047_auto_20190729_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritymenu',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='educationdegree',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='filemanage',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='nationinfo',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='provincecitycountry',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='registeruserinfo',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='roleauthority',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='roleinfo',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='unitnature',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='userauthority',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='workinghistory',
            name='explain',
            field=models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='说明'),
        ),
    ]
