# Generated by Django 2.2.2 on 2019-08-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0048_auto_20190801_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='former_occupation',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='former_occupation',
            field=models.CharField(blank=True, help_text='原职业', max_length=20, null=True, verbose_name='原职业'),
        ),
    ]
